base_config: opt/configs/config_for_tracking/replica/replica.yaml

exp_name: replica/office0
device: cuda:0
ckpt: /home/Project/WACV/PlenoxelTracking_public/ckpt/ckpt.npz

data_specs:
  data_path: /mnt/data3/plenoxelVO/Replica/office0