log_dir: './logs'
dataset: replica

vis_every: 100
save_every: 10000

data_specs:
  max_depth: 10
  depth_scale: 6553.5

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5

rendering:
  step_size: 0.5                                # Step size, in normalized voxels
  sigma_thresh: 1e-10                           # Voxels with sigmas < this are ignored
  stop_thresh: 1e-7                             # Stops rendering if the remaining light intensity/termination, in [0, 1]
  near_clip: 0.0
  N_samples: 32
  N_surface: 0
  N_importance: 12
  lindisp: False
  perturb: 0.0
  empty_space_brightness: 1.0
  last_sample_opaque: False
  use_spheric_clip: False

criteria:
  rgb_weight: 0.5
  depth_weight: 1

tracking:
  cam_lr: 0.001
  seperate_LR: False
  lr_scale_rot: 10
  const_speed_assumption: True

  iter_num: 1
  epoch_num: 90
  batch_size: 4096