base_config: opt/configs/config_for_tracking/replica/replica.yaml

exp_name: replica/room0
device: cuda:0
ckpt: /home/Project/PlenoxTracking_depth/builtmap/ckpt_r0.npz

data_specs:
  data_path: /mnt/data3/plenoxelVO/Replica/room0