base_config: opt/configs/config_for_tracking/scannet/scannet.yaml

exp_name: scannet/0169
device: cuda:0
ckpt: /home/Project/PlenoxTracking_depth/archive/builtmap/0169.npz

data_specs:
  data_path: /mnt/data3/scannet-after/scene0169_00